main: net.problemzone.troubles.Main
version: 0.4
name: Troubles
authors: [JustFloooo]
depend: [ProtocolLib]
softdepend: [CloudNet-Bridge]
api-version: 1.13
commands:
  start:
    description: Start the Game
    usage: /start [time >= 5]
    permission: troubles.command.start
  cancel:
    description: Cancels the Countdown
    usage: /cancel
    permission: troubles.command.cancel
  scorpse:
    description: scorpse
    usage: /scorpse
    permission: troubles.command.scorpse