main: net.problemzone.troubles.Main
version: 0.2
name: Troubles
authors: [JustFloooo]
api-version: 1.13
commands:
  start:
    description: Start the Game
    usage: /start [time > 5]
    permission: troubles.command.*